# version: '3.8'

services:
  db:
    image: postgres:15 # name of image should be from DockerHub
    restart: always
    environment: # pay attension that this lines should not be if github is public
      POSTGRES_DB: EqualStageDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      
  app:
  # image : "<username_dockerhub>/equal_stage_platform"
    build: . # this line sasying that the image is built from files and not search from dockerhub
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    # command: ./mvnw spring-boot:run --> this is a commend taht will run on startup
    environment: # pay attension that this lines should not be if github is public
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/EqualStageDB
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

    volumes:
      - .:/app
      
volumes:
  pgdata:

