version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: equal_stage_postgres
    environment:
      POSTGRES_DB: equal_stage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/equal_stage_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    volumes:
      - .:/app
      
volumes:
<<<<<<< HEAD
  pgdata:

=======
  postgres_data:
>>>>>>> origin/dev-michal
