spring.datasource.url=jdbc:postgresql://localhost:5432/EqualStageDB
spring.datasource.username=user
spring.datasource.password=password
# spring.jpa.hibernate.ddl-auto=update
# To clear the database on startup, comment the line above and uncomment the line below
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.application.name=dev
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.com.equal_stage_platform=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.root=INFO