spring.datasource.url=jdbc:postgresql://localhost:5432/EqualStageDB
spring.datasource.username=user
spring.datasource.password=password
# spring.jpa.hibernate.ddl-auto=update
# To clear the database on startup, comment the line above and uncomment the line below
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.application.name=dev
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true

# JWT
jwt.secret=SuperSecretKeyForJWTGeneration123456
# 15 minutes
jwt.expiration=900000
# 7 days
jwt.refreshExpiration=604800000

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# --- Mail Configuration (Ethereal Email) ---
spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=lacy55@ethereal.email
spring.mail.password=CpXQdQyG7WTPkc5uSY
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
