package com.equal_stage_platform.dev.config;

import java.util.Map;
import java.util.Set;

import com.equal_stage_platform.dev.model.enums.Area;

public class fakerHebNames {
    private static final Map<String, String> HEBREW_TO_ENGLISH_LAST_NAMES = Map.ofEntries(
        Map.entry("כהן", "Cohen"),
        Map.entry("לוי", "Levi"),
        Map.entry("מזרחי", "Mizrahi"),
        Map.entry("פרץ", "Peretz"),
        Map.entry("ביטון", "Biton"),
        Map.entry("דיין", "Dayan"),
        Map.entry("עזריה", "Azaria"),
        Map.entry("חדד", "Haddad"),
        Map.entry("אוחנה", "Ohana"),
        Map.entry("אסולין", "Assouline"),
        Map.entry("אלבז", "Elbaz"),
        Map.entry("שטרית", "Shitrit"),
        Map.entry("עובדיה", "Ovadia"),
        Map.entry("מלול", "Malul"),
        Map.entry("סויסה", "Swisa"),
        Map.entry("לויון", "Levion"),
        Map.entry("אליהו", "Eliyahu"),
        Map.entry("ברדוגו", "Bardugo"),
        Map.entry("שושן", "Shoshan"),
        Map.entry("סבן", "Saban"),
        Map.entry("צרפתי", "Tzarfati"),
        Map.entry("גבאי", "Gabai"),
        Map.entry("תורג'מן", "Turgeman"),
        Map.entry("חזיזה", "Haziza"),
        Map.entry("ברוך", "Baruch"),
        Map.entry("נגארי", "Nagari"),
        Map.entry("חיון", "Chayon"),
        Map.entry("אוחיון", "Ohayon"),
        Map.entry("אברג'יל", "Abargil"),
        Map.entry("אזולאי", "Azoulay"),
        Map.entry("אדיב", "Adib"),
        Map.entry("חיים", "Chaim"),
        Map.entry("צדוק", "Tzadok"),
        Map.entry("פרידמן", "Friedman"),
        Map.entry("גולן", "Golan"),
        Map.entry("סיטבון", "Sitbon"),
        Map.entry("ללוש", "Lellouche"),
        Map.entry("חלפון", "Halfon"),
        Map.entry("אדרי", "Edri"),
        Map.entry("רז", "Raz"),
        Map.entry("רוזנבלום", "Rosenblum"),
        Map.entry("בניסטי", "Benisti"),
        Map.entry("אלקיים", "Elkayam"),
        Map.entry("בן שושן", "Ben Shoshan"),
        Map.entry("זוארץ", "Zuaratz"),
        Map.entry("עמר", "Amar"),
        Map.entry("דמארי", "Damari"),
        Map.entry("ממן", "Maman"),
        Map.entry("רומנו", "Romano"),
        Map.entry("כץ", "Katz"),
        Map.entry("רבינוביץ'", "Rabinowitz"),
        Map.entry("זלמן", "Zalman"),
        Map.entry("בוזגלו", "Buzaglo"),
        Map.entry("עיני", "Eini"),
        Map.entry("לוזון", "Luzon"),
        Map.entry("ברקת", "Barkat"),
        Map.entry("נחמני", "Nachmani"),
        Map.entry("חסון", "Hasson"),
        Map.entry("פדידה", "Fadida"),
        Map.entry("בן דוד", "Ben David"),
        Map.entry("שוקרון", "Shukron"),
        Map.entry("עטר", "Atar"),
        Map.entry("מלכה", "Malka"),
        Map.entry("ליס", "Lis"),
        Map.entry("גואטה", "Guetta"),
        Map.entry("חביב", "Haviv"),
        Map.entry("רואס", "Roas"),
        Map.entry("ברזילי", "Barzilai"),
        Map.entry("ברנר", "Brenner"),
        Map.entry("קירשנבאום", "Kirshenbaum"),
        Map.entry("מאירי", "Meiri"),
        Map.entry("עידן", "Idan"),
        Map.entry("רייכמן", "Reichman"),
        Map.entry("לנדאו", "Landau"),
        Map.entry("קליין", "Klein"),
        Map.entry("מילר", "Miller"),
        Map.entry("כהנא", "Kahana"),
        Map.entry("אלפסי", "Alfasi"),
        Map.entry("מור", "Mor"),
        Map.entry("פינטו", "Pinto"),
        Map.entry("בורוכוב", "Borochov"),
        Map.entry("קורקוס", "Korkus"),
        Map.entry("טולדנו", "Toledano"),
        Map.entry("רוזן", "Rosen"),
        Map.entry("רביבו", "Revivo"),
        Map.entry("פרנקל", "Frankel"),
        Map.entry("בלום", "Blum"),
        Map.entry("בן הרוש", "Ben Harush"),
        Map.entry("זגורי", "Zaguri"),
        Map.entry("קמחי", "Kimchi"),
        Map.entry("חנוכה", "Chanukah"),
        Map.entry("זילברמן", "Zilberman"),
        Map.entry("אלגרבלי", "Elgrably"),
        Map.entry("שיין", "Shine"),
        Map.entry("ברוש", "Brosh"),
        Map.entry("קלדרון", "Calderon"),
        Map.entry("אליאס", "Elyas"),
        Map.entry("שלמה", "Shlomo"),
        Map.entry("אלתר", "Alter"),
        Map.entry("זליג", "Zelig"),
        Map.entry("מינץ", "Mintz"),
        Map.entry("עמאר", "Amar"),
        Map.entry("מאור", "Maor"),
        Map.entry("פז", "Paz"),
        Map.entry("בובליל", "Bublil"),
        Map.entry("דהרי", "Dahari"),
        Map.entry("שינדלר", "Schindler"),
        Map.entry("לוגסי", "Lugasi"),
        Map.entry("ליבוביץ", "Leibowitz"),
        Map.entry("וינשטיין", "Weinstein"),
        Map.entry("אייזנברג", "Eisenberg"),
        Map.entry("מויאל", "Moyal"),
        Map.entry("ברזני", "Barzani"),
        Map.entry("רוזנברג", "Rosenberg"),
        Map.entry("טואג", "Toeg"),
        Map.entry("סבח", "Sabach"),
        Map.entry("אדלר", "Adler"),
        Map.entry("וינר", "Weiner"),
        Map.entry("אביטל", "Avital"),
        Map.entry("סולומון", "Solomon"),
        Map.entry("גולדמן", "Goldman"),
        Map.entry("בוסקילה", "Bouskila"),
        Map.entry("שימחוביץ", "Simchovitz"),
        Map.entry("סלומון", "Salomon"),
        Map.entry("הרשקוביץ", "Hershkowitz"),
        Map.entry("קרמר", "Kramer"),
        Map.entry("רינגל", "Ringel"),
        Map.entry("יעקובוביץ'", "Yakubovich"),
        Map.entry("דהן", "Dahan"),
        Map.entry("שוקר", "Shoker"),
        Map.entry("טויטו", "Tuito"),
        Map.entry("שושנה", "Shoshana"),
        Map.entry("מורד", "Morad"),
        Map.entry("בילו", "Bilu"),
        Map.entry("בן סימון", "Ben Simon"),
        Map.entry("זליגמן", "Zeligman"),
        Map.entry("דביר", "Dvir"),
        Map.entry("אלון", "Alon"),
        Map.entry("דרעי", "Deri"),
        Map.entry("נחשון", "Nachshon"),
        Map.entry("בנדיקט", "Benedict"),
        Map.entry("קציר", "Katzir"),
        Map.entry("צור", "Tzur"),
        Map.entry("ריבלין", "Rivlin"),
        Map.entry("עמרני", "Amrani"),
        Map.entry("אבוחצירה", "Abuhatzeira"),
        Map.entry("חביביאן", "Havivian"),
        Map.entry("לביא", "Lavi"),
        Map.entry("דנינו", "Danino"),
        Map.entry("שאול", "Shaul"),
        Map.entry("רוזנטל", "Rosenthal"),
        Map.entry("שיינר", "Shayner"),
        Map.entry("ציון", "Zion"),
        Map.entry("בארי", "Baari"),
        Map.entry("וייס", "Weiss"),
        Map.entry("דרור", "Dror"),
        Map.entry("מרציאנו", "Marciano"),
        Map.entry("מועלם", "Moalem"),
        Map.entry("גיגי", "Gigi"),
        Map.entry("רייכנברג", "Reichenberg"),
        Map.entry("הורוביץ", "Horowitz"),
        Map.entry("פוגל", "Fogel"),
        Map.entry("כפיר", "Kfir"),
        Map.entry("פנחס", "Pinchas"),
        Map.entry("שטרן", "Stern"),
        Map.entry("ברגר", "Berger"),
        Map.entry("ברודני", "Brodny"),
        Map.entry("אלקבץ", "Elkabetz"),
        Map.entry("בן שבת", "Ben Shabat"),
        Map.entry("אדלמן", "Adelman"),
        Map.entry("מנדל", "Mendel"),
        Map.entry("קרלוס", "Carlos"),
        Map.entry("שגב", "Segev"),
        Map.entry("סעדון", "Saadon"),
        Map.entry("שיינפלד", "Sheinfeld"),
        Map.entry("בלנק", "Blank"),
        Map.entry("ויינרוט", "Weinroth"),
        Map.entry("לוין", "Levin"),
        Map.entry("עוזרי", "Ozery"),
        Map.entry("טרבלסי", "Trabelsi"),
        Map.entry("נגר", "Nagar"),
        Map.entry("עזרן", "Ezran"),
        Map.entry("בן זקן", "Ben Zaken"),
        Map.entry("נחום", "Nahum"),
        Map.entry("קריספל", "Crispel")
);

private static final Map<String, String> HEBREW_TO_ENGLISH_FIRST_NAMES = Map.ofEntries(
        Map.entry("איתי", "Itay"),
        Map.entry("עידן", "Idan"),
        Map.entry("נועם", "Noam"),
        Map.entry("אורי", "Ori"),
        Map.entry("יובל", "Yuval"),
        Map.entry("רועי", "Roi"),
        Map.entry("דניאל", "Daniel"),
        Map.entry("עומר", "Omer"),
        Map.entry("שחר", "Shahar"),
        Map.entry("אדם", "Adam"),
        Map.entry("תומר", "Tomer"),
        Map.entry("ניר", "Nir"),
        Map.entry("טל", "Tal"),
        Map.entry("יואב", "Yoav"),
        Map.entry("אלון", "Alon"),
        Map.entry("גיא", "Guy"),
        Map.entry("יאיר", "Yair"),
        Map.entry("מתן", "Matan"),
        Map.entry("נדב", "Nadav"),
        Map.entry("אופיר", "Ofir"),
        Map.entry("ליאם", "Liam"),
        Map.entry("עידו", "Ido"),
        Map.entry("אלעד", "Elad"),
        Map.entry("אביב", "Aviv"),
        Map.entry("עמית", "Amit"),
        Map.entry("שגיא", "Sagi"),
        Map.entry("שמעון", "Shimon"),
        Map.entry("יונתן", "Yonatan"),
        Map.entry("אריאל", "Ariel"),
        Map.entry("משה", "Moshe"),
        Map.entry("שלומי", "Shlomi"),
        Map.entry("רון", "Ron"),
        Map.entry("עמנואל", "Emmanuel"),
        Map.entry("יהונתן", "Yehonatan"),
        Map.entry("צבי", "Zvi"),
        Map.entry("שלמה", "Shlomo"),
        Map.entry("אלחנן", "Elchanan"),
        Map.entry("אברהם", "Avraham"),
        Map.entry("שמואל", "Shmuel"),
        Map.entry("יצחק", "Yitzhak"),
        Map.entry("אליהו", "Eliyahu"),
        Map.entry("איל", "Eyal"),
        Map.entry("צור", "Tzur"),
        Map.entry("רמי", "Rami"),
        Map.entry("בנימין", "Binyamin"),
        Map.entry("אבנר", "Avner"),
        Map.entry("יגאל", "Yigal"),
        Map.entry("חיים", "Chaim"),
        Map.entry("זיו", "Ziv"),
        Map.entry("מנחם", "Menachem"),
        Map.entry("רפי", "Rafi"),
        Map.entry("אוהד", "Ohad"),
        Map.entry("עוז", "Oz"),
        Map.entry("עמוס", "Amos"),
        Map.entry("אמיר", "Amir"),
        Map.entry("אהרון", "Aharon"),
        Map.entry("גדעון", "Gideon"),
        Map.entry("ברוך", "Baruch"),
        Map.entry("יאשה", "Yasha"),
        Map.entry("טום", "Tom"),
        Map.entry("קובי", "Kobi"),
        Map.entry("גיל", "Gil"),
        Map.entry("אשר", "Asher"),
        Map.entry("אליאב", "Eliyav"),
        Map.entry("זוהר", "Zohar"),
        Map.entry("אופק", "Ofek"),
        Map.entry("דור", "Dor"),
        Map.entry("מאור", "Maor"),
        Map.entry("עדי", "Adi"),
        Map.entry("רז", "Raz"),
        Map.entry("אלמוג", "Almog"),
        Map.entry("סער", "Saar"),
        Map.entry("ישי", "Yishai"),
        Map.entry("שילה", "Sheila"),
        Map.entry("תום", "Tom"),
        Map.entry("אסף", "Asaf"),
        Map.entry("מעיין", "Maayan"),
        Map.entry("אילון", "Elon"),
        Map.entry("דרור", "Dror"),
        Map.entry("חזי", "Hezi"),
        Map.entry("אבשלום", "Avshalom"),
        Map.entry("איתן", "Eitan"),
        Map.entry("דביר", "Dvir"),
        Map.entry("עמרי", "Omri"),
        Map.entry("שימי", "Shimi"),
        Map.entry("יוסי", "Yossi"),
        Map.entry("גדי", "Gadi"),
        Map.entry("צחי", "Tzachi"),
        Map.entry("גד", "Gad"),
        Map.entry("עוזי", "Uzi"),
        Map.entry("עמרם", "Amram"),
        Map.entry("יצחקי", "Yitzhaki"),
        Map.entry("פנחס", "Pinchas"),
        Map.entry("נחום", "Nachum"),
        Map.entry("ירון", "Yaron"),
        Map.entry("יאשיהו", "Yoshiyahu"),
        Map.entry("תאופיק", "Tawfik"),
        Map.entry("ניב", "Niv"),
        Map.entry("מקסים", "Maxim"),
        Map.entry("ויקטור", "Victor"),
        Map.entry("אלכס", "Alex"),
        Map.entry("ולדי", "Vlady"),
        Map.entry("אנטון", "Anton"),
        Map.entry("ארתור", "Arthur"),
        Map.entry("ראובן", "Reuven"),
        Map.entry("מאיר", "Meir"),
        Map.entry("סימון", "Simon"),
        Map.entry("בני", "Benny"),
        Map.entry("בועז", "Boaz"),
        Map.entry("הראל", "Harel"),
        Map.entry("סהר", "Sahar"),
        Map.entry("עומרי", "Omri"),
        Map.entry("נמרוד", "Nimrod"),
        Map.entry("ארז", "Erez"),
        Map.entry("שון", "Sean"),
        Map.entry("אורן", "Oren"),
        Map.entry("דקל", "Dekel"),
        Map.entry("חן", "Chen"),
        Map.entry("ליאון", "Leon"),
        Map.entry("אלירן", "Eliran"),
        Map.entry("אור", "Or"),
        Map.entry("שחרור", "Shacharur"),
        Map.entry("בר", "Bar"),
        Map.entry("רפאל", "Raphael"),
        Map.entry("מרדכי", "Mordechai"),
        Map.entry("יהושע", "Yehoshua"),
        Map.entry("דויד", "David"),
        Map.entry("חגי", "Haggai"),
        Map.entry("אלקנה", "Elkana"),
        Map.entry("אפרים", "Ephraim"),
        Map.entry("עמיאל", "Amiel"),
        Map.entry("עזריה", "Azaria"),
        Map.entry("שאול", "Shaul"),
        Map.entry("זכריה", "Zechariah"),
        Map.entry("כפיר", "Kfir"),
        Map.entry("דורון", "Doron"),
        Map.entry("עוזיאל", "Uziel"),
        Map.entry("יואל", "Yoel"),
        Map.entry("שבתאי", "Shabtai"),
        Map.entry("ליאב", "Liav"),
        Map.entry("תהל", "Tahal"),
        Map.entry("ברק", "Barak"),
        Map.entry("איהב", "Aihab"),
        Map.entry("חוסאם", "Hussam"),
        Map.entry("שגב", "Segev"),
        Map.entry("רונן", "Ronen"),
        Map.entry("גלעד", "Gilad"),
        Map.entry("אליעד", "Eliad"),
        Map.entry("שקד", "Shaked"),
        Map.entry("טליה", "Talia"),
        Map.entry("גל", "Gal"),
        Map.entry("מתניה", "Matanya"),
        Map.entry("אשרי", "Ashri"),
        Map.entry("יחזקאל", "Yehezkel"),
        Map.entry("עטר", "Atar"),
        Map.entry("אביעד", "Aviad"),
        Map.entry("גבריאל", "Gabriel"),
        Map.entry("רם", "Ram"),
        Map.entry("נדיר", "Nadir"),
        Map.entry("סאלח", "Saleh"),
        Map.entry("קאסם", "Qasem"),
        Map.entry("תמיר", "Tamir"),
        Map.entry("אביה", "Aviya"),
        Map.entry("אלדר", "Eldar"),
        Map.entry("איליה", "Ilya"),
        Map.entry("נריה", "Neria"),
        Map.entry("שלו", "Shalev"),
        Map.entry("רואי", "Roee"),
        Map.entry("אדיר", "Adir"),
        Map.entry("מנשה", "Menashe"),
        Map.entry("ציון", "Zion"),
        Map.entry("נסים", "Nissim"),
        Map.entry("יוסוף", "Yousef"),
        Map.entry("נחמן", "Nachman"),
        Map.entry("כרים", "Karim"),
        Map.entry("אלירז", "Eliraz"),
        Map.entry("ירין", "Yarin"),
        Map.entry("חנוך", "Chanokh"),
        Map.entry("צורי", "Tzuri"),
        Map.entry("אמנון", "Amnon"),
        Map.entry("יהב", "Yahav"),
        Map.entry("אחיה", "Ahiya"),
        Map.entry("איה", "Aya")
);
    private static final Set<String> CITIES = Set.of(
            "תל אביב", "ירושלים", "חיפה", "באר שבע", "פתח תקווה", "אשדוד", "נתניה", "רמת גן",
            "ראשון לציון", "רחובות", "כפר סבא", "קריית שמונה", "אילת", "מודיעין", "נס ציונה",
            "רעננה", "אשקלון", "עפולה", "נתיבות", "קריית גת", "בית שמש", "אור יהודה",
            "רמלה", "לוד", "קריית מלאכי", "גבעתיים", "בני ברק", "אור עקיבא", "זכרון יעקב",
            "מעלות תרשיחא", "נהריה", "עכו", "קריית ים", "קריית מוצקין", "קריית אתא", "חדרה",
             "כפר יונה", "שדרות", "קריית אונו", "גבעת שמואל", "יהוד",
            "אבן יהודה", "מזכרת בתיה", "גני תקווה", "קדימה צורן", "צפת", "טבריה", "ירוחם",
            "מגדל העמק", "קריית ביאליק", "קריית סביון", "כפר תבור"
            );
    private static final Map<String, Area> CITY2AREA = Map.ofEntries(
        Map.entry("תל אביב", Area.CENTER),        Map.entry("ירושלים", Area.CENTER),        Map.entry("חיפה", Area.NORTH),        Map.entry("באר שבע", Area.SOUTH),
        Map.entry("פתח תקווה", Area.CENTER),        Map.entry("אשדוד", Area.SOUTH),        Map.entry("נתניה", Area.CENTER),        Map.entry("רמת גן", Area.CENTER),
        Map.entry("ראשון לציון", Area.CENTER),       Map.entry("רחובות", Area.CENTER),        Map.entry("כפר סבא", Area.CENTER),        Map.entry("קריית שמונה", Area.NORTH),
        Map.entry("אילת", Area.SOUTH),        Map.entry("מודיעין", Area.CENTER),       Map.entry("נס ציונה", Area.CENTER),        Map.entry("רעננה", Area.CENTER),
        Map.entry("אשקלון", Area.SOUTH),        Map.entry("טבריה", Area.NORTH),        Map.entry("עפולה", Area.NORTH),        Map.entry("נתיבות", Area.SOUTH),
        Map.entry("קריית גת", Area.SOUTH),        Map.entry("בית שמש", Area.CENTER),        Map.entry("אור יהודה", Area.CENTER),        
        Map.entry("לוד", Area.CENTER),        Map.entry("קריית מלאכי", Area.SOUTH),        Map.entry("גבעתיים", Area.CENTER),        Map.entry("בני ברק", Area.CENTER),
        Map.entry("אור עקיבא", Area.CENTER),        Map.entry("זכרון יעקב", Area.CENTER),        Map.entry("מעלות תרשיחא", Area.NORTH),        Map.entry("נהריה", Area.NORTH),
        Map.entry("עכו", Area.NORTH),        Map.entry("קריית ים", Area.NORTH),        Map.entry("קריית מוצקין", Area.NORTH),        Map.entry("קריית אתא", Area.NORTH),
        Map.entry("חדרה", Area.CENTER),        Map.entry("רמלה", Area.CENTER),        Map.entry("כפר יונה", Area.CENTER),
        Map.entry("שדרות", Area.SOUTH),        Map.entry("קריית אונו", Area.CENTER),        Map.entry("גבעת שמואל", Area.CENTER),        Map.entry("יהוד", Area.CENTER),
        Map.entry("אבן יהודה", Area.CENTER),        Map.entry("מזכרת בתיה", Area.CENTER),        Map.entry("גני תקווה", Area.CENTER),        Map.entry("קדימה צורן", Area.CENTER),
        Map.entry("צפת", Area.NORTH),        Map.entry("ירוחם", Area.SOUTH),        Map.entry("מגדל העמק", Area.NORTH),
        Map.entry("קריית ביאליק", Area.NORTH),        Map.entry("קריית סביון", Area.CENTER)
    );
    private static final Set<String> Topics = Set.of(
        "הדרך לשביל הזהב", "המסע אל האור", "החיפוש אחר האמת", "המסע אל תוך הנפש",
        "לקום מחדש", "הכרות מחודשת", "המסע אל האני", "המסע אל האור הפנימי",
        "התעוררות", "צחוק הגורל", "רגע לפני השקט", "עולמות מקבילים", "שברי זכרון", "ניצוץ של תקווה",
        "בין קירות הלב", "כשקולות דוממים", "כוחה של מילה", "הצלילים שבפנים",
        "לאן הלב פונה", "היופי שבשבר", "קווים לדמותי", "לגעת בקצה החלום",
        "הזדמנות שנייה", "דרך של אהבה", "החיים על פי...", "צללים של אור",
        "בין אור לחושך", "נקודת מפנה", "לראות מעבר", "מה שלמדתי מהכאב",
        "בחזרה לעצמי", "על החיים ועל עוד קצת", "חלומות על אמת", "שיעורים שלא נכתבו"
    );
    private static final Set<String> HEBREW_FIRST_NAMES = HEBREW_TO_ENGLISH_FIRST_NAMES.keySet();
    private static final Set<String> HEBREW_LAST_NAMES = HEBREW_TO_ENGLISH_LAST_NAMES.keySet(); 

    public static String randomHebrewFirstName() {
        return HEBREW_FIRST_NAMES.stream()
                .skip((int) (HEBREW_FIRST_NAMES.size() * Math.random()))
                .findFirst()
                .orElse("שם פרטי לא זמין");
    }
    public static String randomHebrewLastName() {
        return HEBREW_LAST_NAMES.stream()
                .skip((int) (HEBREW_LAST_NAMES.size() * Math.random()))
                .findFirst()
                .orElse("שם משפחה לא זמין");
    }
    public static String heb2eng_firstName(String hebrewName) {
        return HEBREW_TO_ENGLISH_FIRST_NAMES.get(hebrewName);
    }
    public static String heb2eng_lastName(String hebrewName) {
        return HEBREW_TO_ENGLISH_LAST_NAMES.get(hebrewName);
    }
    public static String randomCity() {
        return CITIES.stream()
                .skip((int) (CITIES.size() * Math.random()))
                .findFirst()
                .orElse("עיר לא זמינה");
    }
    public static Area city2area(String city) {
        return CITY2AREA.getOrDefault(city, Area.ONLINE_ONLY);
    }
    public static String randomTopic() {
        return Topics.stream()
                .skip((int) (Topics.size() * Math.random()))
                .findFirst()
                .orElse("נושא לא זמין");
    }
}
